### ISSUE TITLE
Implicit declarations when using `--enable-libc-includes`

### ISSUE THREAD

**Issue by firasuke** [skarnet/nsss#3]
Hey there,

Thank you for your time and effort!

I am facing a bunch of errors related to nsss's `grp.h` overriding musl's `grp.h` after using `--enable-libc-includes`.

The errors are related to implicit declarations of functions (e.g. `initgroups`):

```c
setugid.c:55:13: error: implicit declaration of function 'initgroups'; did you mean 'setgroups'? [-Wimplicit-function-declaration]
```

These can be solved by using musl's `grp.h` or by removing the preprocessor condition on [L72 in nsss's `grp.h`](https://github.com/skarnet/nsss/blob/master/src/include/nsss/grp.h#L72):
```c
#if defined(__GNU__) && (defined(_BSD_SOURCE) || defined(_DEFAULT_SOURCE))
```

So that the [definition of `initgroups` on L75](https://github.com/skarnet/nsss/blob/master/src/include/nsss/grp.h#L75) is enabled.

Is this intended? and can the condition be modified to accomodate for musl libc?

Thanks in advance!

**Comment by skarnet** [comment]
Yeah I think you're right, the `__GNU__` test is wrong here. Fixed in git, release coming with the next batch of skaware.
