### ISSUE TITLE
Missing define in `nsss/shadow.h`

### ISSUE THREAD

**Issue by firasuke** [skarnet/nsss#4]
Hey there,

I appreciate your work on the project.

I was wondering if there's a need to define the `SHADOW` symbol inside `nsss/shadow.h`. For example here's what musl's `shadow.h` does:

```c
#define	SHADOW "/etc/shadow"
```

Or is this not intended to be used with `nsss`?

Thanks in advance!

**Comment by skarnet** [comment]
nsss doesn't use it at all, but some userspace may want it, so I guess I'll add it.

**Comment by skarnet** [comment]
Fixed in git, release coming whenever I get to the next skaware release.
